#!/usr/bin/env node
/* Builds the library bundles from the script blocks in index.html, so other
   programs (the attack simulator, the list builder) can call Tankiness.rate
   without loading the page. index.html stays the only source of truth;
   test/dist.test.mjs fails if dist/ falls behind it.

     dist/tankiness.js    classic <script src> (window.Tankiness) and Node require()
     dist/tankiness.mjs   ES module: import Tankiness, { Engine, Data } from ...

   `node build.mjs` writes them; `node build.mjs --check` only reports drift. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { scriptSource } from './test/load.mjs';

const root = path.dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

export function bundles() {
  const blocks = ['engine', 'data', 'tankiness'].map(id => scriptSource(id).trim()).join('\n\n');
  const header = `/* Necromunda (N26) Tankiness Simulator, library build ${pkg.version}.
   Generated by build.mjs from index.html; do not edit. ${pkg.homepage}
   Tankiness.rate(fighter, options) is documented in the README. */\n`;
  const js = header +
    '(function (root) {\n"use strict";\n' +
    'var module = undefined;\n' +   // the blocks' CommonJS hooks stay inert inside the wrapper
    blocks + '\n' +
    'root.Engine = Engine; root.Data = Data; root.Tankiness = Tankiness;\n' +
    '})(typeof globalThis !== "undefined" ? globalThis : this);\n' +
    'if (typeof module !== "undefined" && module.exports) { module.exports = globalThis.Tankiness; module.exports.Engine = globalThis.Engine; module.exports.Data = globalThis.Data; }\n';
  const mjs = header + blocks + '\n' +
    'export { Engine, Data, Tankiness };\nexport default Tankiness;\n';
  return { 'dist/tankiness.js': js, 'dist/tankiness.mjs': mjs };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  const out = bundles();
  let stale = 0;
  for (const [rel, body] of Object.entries(out)) {
    const file = path.join(root, rel);
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (current === body) continue;
    stale++;
    if (check) { console.error(`${rel} is out of date; run \`npm run build\``); continue; }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, body);
    console.log(`wrote ${rel} (${body.length} bytes)`);
  }
  if (check && stale) process.exit(1);
  if (!stale) console.log('dist/ is up to date');
}
